# Generated by Django 4.0.3 on 2022-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('departamentId', models.AutoField(primary_key=True, serialize=False)),
                ('departamentName', models.CharField(max_length=500)),
            ],
        ),
    ]
