# Generated by Django 4.0.3 on 2022-03-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoritmosApp', '0002_alter_departments_departamentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('grafoId', models.AutoField(primary_key=True, serialize=False)),
                ('nodos', models.TextField()),
                ('aristas', models.TextField()),
            ],
        ),
    ]
